---
ansible_connection: local
namespace:

openshift_cluster_content:

- object: secrets
  content:
    - name: Create businesscentral-app-secret
      file: "{{ inventory_dir }}/../templates/businesscentral-app-secret-template.yml"
      params:
      namespace: "{{ namespace }}"
      tags:
      - create-secrets
      - deploy-authoring-template

- object: secrets
  content:
    - name: Create kieserver-app-secret
      file: "{{ inventory_dir }}/../templates/kieserver-app-secret-template.yml"
      params:
      namespace: "{{ namespace }}"
      tags:
      - create-secrets
      - deploy-authoring-template

- object: rhpam71-image-streams
  content:
    - name: Import RHPAM 7.1 Image Streams
      file: "{{ inventory_dir }}/../templates/rhpam71-image-streams.yml"
      params:
      namespace: "{{ namespace }}"
      tags:
      - import-imagestreams
      - deploy-trial-ephemeral-template
      - deploy-authoring-template

- object: rhpam71-trial-ephemeral-deploy
  content:
    - name: Deploy RHPAM 7.1 Trial Ephemeral App
      template: "{{ inventory_dir }}/../templates/rhpam71-trial-ephemeral.yml"
      params: "{{ inventory_dir }}/../params/rhpam71-trial-ephemeral-params"
      params_from_vars:
        IMAGE_STREAM_NAMESPACE: "{{ namespace }}"
      namespace: "{{ namespace }}"
      tags:
      - deploy-trial-ephemeral-template

- object: rhpam71-authoring-deploy
  content:
    - name: Deploy RHPAM 7.1 Authoring App
      template: "{{ inventory_dir }}/../templates/rhpam71-authoring.yml"
      params: "{{ inventory_dir }}/../params/rhpam71-authoring-params"
      params_from_vars:
        IMAGE_STREAM_NAMESPACE: "{{ namespace }}"
      namespace: "{{ namespace }}"
      tags:
      - deploy-authoring-template
