---
ansible_connection: local
namespace:

openshift_cluster_content:
- object: secrets
  content:
    - name: Create businesscentral-app-secret
      file: "{{ inventory_dir }}/../templates/businesscentral-app-secret-template.yml"
      params:
      namespace: "{{ namespace }}"
      tags:
      - all
      - create-secrets
- object: secrets
  content:
    - name: Create kieserver-app-secret
      file: "{{ inventory_dir }}/../templates/kieserver-app-secret-template.yml"
      params:
      namespace: "{{ namespace }}"
      tags:
      - all
      - create-secrets
- object: rhpam71-image-streams
  content:
    - name: Import RHPAM 7.1 Image Streams
      file: "{{ inventory_dir }}/../templates/rhpam71-image-streams.yml"
      params:
      namespace: "{{ namespace }}"
      tags:
      - all
      - import-imagestreams
- object: rhpam71-trial-ephemeral-deploy
  content:
    - name: Deploy RHPAM 7.1 Trial Ephemeral App
      template: "rhpam71-trial-ephemeral"
      params: "{{ inventory_dir }}/../params/rhpam71-trial-ephemeral-params"
      params_from_vars:
        IMAGE_STREAM_NAMESPACE: "{{ namespace }}"
      namespace: "{{ namespace }}"
      tags:
      - all
      - deploy-trial-ephemeral-template
